### ISSUE TITLE
Spawlocations - Extention

### ISSUE THREAD

**Issue by byMysterio** [HGLabor/HGLaborFFA2.0#17]
Man spawnt teilweise in der Luft und stirbt an Falldamage, sowie man auch im Boden spawnen kann und dann erstickt. Das passiert bei mir relativ oft ca. zu 30%, wenn ich spawne.

**Comment by oneeegithub** [comment]
Ich hab myb ne Lösung

**Comment by copyandexecute** [comment]
Duplicate of Spawnlocations #16
