### ISSUE TITLE
Map Resett Bug

### ISSUE THREAD

**Issue by byMysterio** [HGLabor/HGLaborFFA2.0#19]
Beim Map Resett werden manche teile der Map nicht resettet, daraus resultiert, dass man in z.B. Löchern, die eigentlich wieder weg sind rum buggt, dabei befindet man sich auf der Höhe, auf welcher man eigentlich sein sollte aber kann sich kaum bewegen und nicht springen, Hits von anderen Spielern geben einen dabei auch Knockback.

**Comment by copyandexecute** [comment]
Ich update mal wordledit

**Comment by oneeegithub** [comment]
@copyandexecute ich hab ne lösung bin mir nich zu 100% sicher aber diese unsichtbaren blöcke werden bei blockupdates normal d.h. zu kannst beim worldreset einfach alles zu wasser machen und dann erst resetten hier noch ein video wo ichs getestet habe:  https://drive.google.com/file/d/1mGpP3xW0O-_NiXUzScnIBpJfX492ECA8/view?usp=sharing

Ich hoffe ich konnte helfen
