### ISSUE TITLE
Mögliche Lösung von den Spawnbugs(Falldamage und ersticken im Block)

### ISSUE THREAD

**Issue by oneeegithub** [HGLabor/HGLaborFFA2.0#20]
Ich habe vielleicht (ich kenne mich nicht so mega gut aus aber bei meinen tests hat es funktioniert) eine Lösung für das Problem, dass man manchmal in der Luft oder im Boden spawnt nachdem man ein Kit ausgewählt hat. Ich glaube am besten wäre es wenn mich jemand auf DC added dann kann ich das besser beschreiben und in einem issue ist es nicht so gut zum chatten. DC Name: one#3440

**Comment by copyandexecute** [comment]
Duplicate of Spawnlocations #16
