### ISSUE TITLE
Bug dass man in der Luft rumlaggt

### ISSUE THREAD

**Issue by oneeegithub** [HGLabor/HGLaborFFA2.0#21]
Es gibt einen Bug, dass man an bestimmten Stellen in der Luft schwebt
https://drive.google.com/file/d/1Szr-oSCJ1vbpV5hhdmByMpq1vkrf3SYo/view?usp=sharing

**Comment by byMysterio** [comment]
Habe ich schon im Mapresett Bug reported.

**Comment by copyandexecute** [comment]
Duplicate of  Map Resett Bug #19
