### ISSUE TITLE
Map Resett - Gladikasten

### ISSUE THREAD

**Issue by byMysterio** [HGLabor/HGLaborFFA2.0#26]
Durch die neue Map Resett Lösung wird auch der Gladi mit resettet, dies passiert weil die map nicht genau in dem Moment wo sie resettet werden sollte nach dem eigentlich Mapresett.

**Comment by copyandexecute** [comment]
Ja klar wäre davor aber auch passiert?

**Comment by byMysterio** [comment]
Aber weil die Map auch teilweise 10 minuten später noch resettet wird, wird die ganze zeit der gladikasten resettet, wodurch es echt nervig ist damit zu spielen wenn der gegner immer raussrpingen kann.
