### ISSUE TITLE
Bei dem Vampir Kit heilt sich das letzte halbe Herz nicht

### ISSUE THREAD

**Issue by LegendPlay** [HGLabor/HGLaborFFA2.0#67]
Wenn man mit dem **Vampir Kit** jemanden tötet und dadurch ein **extra Herz** bekommt **heilt** sich das letzte halbe Herz **nicht.**

Link zum YouTube Video:
https://youtu.be/MCV4pmboLrg

**Comment by Naaaaaam** [comment]
Ist das nicht so gewollt? Weil das damals zu OP war? Bin mir gerade aber nicht sicher

**Comment by helqless** [comment]
ja man kriegt immer nur ein halbes herz dazu und das limit liegt bei 20

**Comment by Naaaaaam** [comment]
ah ja genau so war es
